services:
  - type: web
    name: webmotors-monitor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
